sudo: required
dist: trusty
language: php

# Versi PHP
php:
  - 7.2

# Branch yang digunakan
branches:
  only:
    - master #-> QA/Staging server

# Build
before_script:
  - cp .env.travis .env

# Test
script:
  - ./vendor/bin/phpunit

# deploy
after_success: